### ISSUE TITLE
When app lives on path, router intercepts routes outside of app.

### ISSUE THREAD

**Issue by ntotten** [yahoo/fluxible-router#108] opened 2015-12-10 19:23 UTC
For example:

If the router is hosted at `example.com/app` and `example.com/page1` has a regular link to `example.com/app`, then the user clicks a navlink to `example.com/app/foo`, then the user hits the back button first the user will go back correctly to `example.com/app`, then if they hit the back button again, fluxible router will incorrectly intercept that route and fail. The correct behavior would be that the user is navigated to `example.com/page1`

The error happens at:

```
class Application extends React.Component {

  render() {
    var Handler = this.props.currentRoute.get('handler');
   // ERROR: this.props.currentRoute === undefined
  }
}
```

Of course this can be handled, but this seems like something that router should do automatically.

**Comment by mridgway** [comment] 2015-12-10 22:44
Weird. Is this in a specific browser or does it happen in all browsers?

**Comment by ntotten** [comment] 2015-12-10 23:52
In chrome it throws an error, in ff it actually just blocks you from going back after the app.

You can repo here: https://auth0.com/pricing. Click the "Documentation" link in the top bar. Then click on one of the quickstarts at the top such as "Regular Web App" then go back twice. You will see the url change back to auth0.com/pricing but stay on the fluxible app which is on auth0.com/docs

**Comment by mridgway** [comment] 2015-12-11 01:13
Got it, I'll take a look to see what's going on.

**Comment by mridgway** [comment] 2015-12-11 01:45
I haven't been able to reproduce this on our apps or examples. The odd thing is that the browser shouldn't even be triggering a `popstate` event since the `/docs` page was a fresh page load, but I confirmed on your page that there is a `popstate`.

**Comment by mridgway** [comment] 2015-12-17 22:42
Let me know if you find anything more on this. Since I can't reproduce, I will close this for now.

**Closed by mridgway** 2015-12-17 22:42 UTC
